# vim: ts=2:sw=2
- hosts: master
  tasks:
    - name: Deploy coredns add-on
      args:
        executable: /bin/bash
      shell: |
        kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml
